name: 'Terraform'

on:
  push:
    branches: [ "main", "release/*" ]

permissions:
  pull-requests: read

jobs:
  CreateSQS:
    runs-on: ubuntu-latest 
    defaults:
      run:
        working-directory: ./infra
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        
    - name: Verificando se bucket está criado
      run: |
            BUCKET_NAME="terraform-tfstate-grupo12-fiap-2024"
            REGION="us-east-1"

            if ! aws s3api head-bucket --bucket "$BUCKET_NAME" 2>/dev/null; then
              echo "Bucket não existe. Criando bucket..."
              aws s3api create-bucket --bucket "$BUCKET_NAME"
            else
              echo "Bucket validado. Processo de upload."
            fi

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
    
    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Plan
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform plan -input=false

    - name: Apply Terraform
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve